


pipeline {
    agent any
    
    tools {
    	maven 'M3'
  	}
  	
  	stages {
    	stage('echo') {
            steps {
                sh 'mvn --version'
            }
        }
        
   	}
    
}