


pipeline {
    agent any
    
    tools {
    	maven 'M3'
  	}
  	
  	stages {
    	stage('echo') {
            steps {
                sh 'mvn --version'
            }
        }
        stage('build') {
            steps {
                sh 'mvn -f arith-api/pom.xml clean package'
            }
            post {
	            always {
	                junit 'arith-api/target/surefire-reports/*.xml'
	            }
         	}
        }
        stage('Staging') {
	        steps {
	           input "Ready to go"
	       }
    	}
    	stage('Deploy / Run') {
	        steps {
	           sh "java -jar arith-api/target/arith-api-0.0.1-SNAPSHOT.jar --server.port=8181 com.example.demo.ArithApiApplication"
	       }
    	}
        
   	}
   	
   	post {
	    always {
	         emailext subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
                to: "Developer",
                body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}"
	    }
	}
    
}